const ADD_LIST = 'ADD_LIST';
const ADD_TODO = 'ADD_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const INCOMPLETE_TODO = 'INCOMPLETE_TODO';
const SAVE_EDIT = 'SAVE_EDIT';
const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';

export {
  ADD_LIST,
  ADD_TODO,
  COMPLETE_TODO,
  DELETE_TODO,
  INCOMPLETE_TODO,
  SAVE_EDIT,
  TOGGLE_COMPLETED,
};
